services:
  - type: web
    name: m-n-a-b-o-t
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        value: "1080317415"
      - key: MAIN_CHANNEL_ID
        value: "-1003181705395"
      - key: ENVIRONMENT
        value: "production"
    healthCheckPath: /
    autoDeploy: true
